import type { GetStaticPaths, GetStaticProps, NextPage } from 'next'
import Head from 'next/head';
import Link from 'next/link';
import { client } from '../api/client';
import styles from '../styles/style.module.css';

type props = {
  blogs: blog[];
}

type blog = {
  id: string,
  title: string,
  content: string
  img: string;
}

const BlogSSR: NextPage<props> = (props) => {
  const { blogs } = props

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Blog Lists(SSR)</h1>
        <div className={styles.nav}>
          <Link href='/'>TOP</Link>
          <Link href='/blog-csr'>CSR</Link>
          <Link href='/blog-ssr'>SSR</Link>
        </div>
        <ul className={styles.list}>
          {blogs.map((blog) => (
            <li key={blog.id}>
              <Link href={`/blog/${blog.id}`}>
                {blog.title}
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export async function getServerSideProps() {
  const blogs = await client.get({ endpoint: 'blogs' })

  return {
    props: { blogs: blogs.contents }
  };
}

export default BlogSSR;